image: k33g/bots-garden-wasi-tinygo:0.0.0

tasks:
  - name: initialize
    before: |

      # ------------------------------------
      # GoLang
      # ------------------------------------

      source /home/gitpod/.gvm/scripts/gvm
      gvm use go1.17.5

      sudo echo "source /home/gitpod/.gvm/scripts/gvm" >> $HOME/.bashrc
      sudo echo "gvm use go1.17.5" >> $HOME/.bashrc

      # ------------------------------------
      # wasmer
      # ------------------------------------
      source /home/gitpod/.wasmer/wasmer.sh
      wasmer --version
      # ------------------------------------
      # wasmtime
      # ------------------------------------
      wasmtime --version
      # ------------------------------------
      # wasmedge dependencies
      # ------------------------------------
      wasmedge --version
      
    init: |
      echo "🚀 initialize"

ports:
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public

vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - rust-lang.rust
    - bungcip.better-toml
    - aaron-bond.better-comments

